### ISSUE TITLE
 Inhomogeneous shape 

### ISSUE THREAD

**Issue by maxfagotto** [gicait/pLitter#9]
I run start.sh in cctv branch with your test.jpg image but I have this issue:

Traceback (most recent call last):
  File "cctv/capture_track.py", line 247, in <module>
    tracker_preds = tracker.update(preds, curr_frame)
  File "/dev/plitter/./Yolov5_StrongSORT_OSNet/trackers/strong_sort/strong_sort.py", line 91, in update
    outputs.append(np.array([x1, y1, x2, y2, track_id, class_id, conf, queue]))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,) + inhomogeneous part.

**Comment by sriramreddyM** [comment]
Could you run start_cctv.sh successfully?

**Comment by maxfagotto** [comment]
> Could you run start_cctv.sh successfully?

Yes I could. I commented cap instance in capture.py and I run start_cctv.sh with your img0 test.jpg.

**Comment by sriramreddyM** [comment]
Great, I will try to reproduce the error from start.sh and fix it sooner in a day or two. If you fix it in mean time please send PR. Thanks.

Please also let me know if you are running it from jetson nano or any other SCB?

**Comment by maxfagotto** [comment]
> Great, I will try to reproduce the error from start.sh and fix it sooner in a day or two. If you fix it in mean time please send PR. Thanks.
> 
> Please also let me know if you are running it from jetson nano or any other SCB?

Now I'm testing on a pc with an Nvidia gt1030 and then in a jetson nano
